- name: app setup
  ansible.builtin.import_role:
    name: common
    task_from: app-setup

- name: go
  ansible.builtin.import_role:
    name: common
    task_from: ngo

- name: system start
  ansible.builtin.import_role:
    name: common
    task_from: systemd