- name: app setup
  ansible.builtin.import_role:
    name: common
    task_from: app-setup

- name: java
  ansible.builtin.import_role:
    name: common
    task_from: java

- name: mysql setup
  ansible.builtin.import_role:
    name: common
    task_from: mysql-setup

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    task_from: systemd