- name: "stop {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: present

- name: recursively remove app directory
  tags:
  - deployment
  ansible.builtin.files:
    path: /app
    state: absent

- name: create app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: directory
  
- name: download catalogue application
  tags:
  - deployment
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /tmp

- name: extract catalogue application
  tags:
  - deployment
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    remote_src: yes

- name: install dependencies
  tags:
  - deployment
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: "restart {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted