- name: app setup
  ansible.builtin.import_role:
    name: common
    task_from: app-setup

- name: app setup
  ansible.builtin.import_role:
    name: common
    task_from: nodejs

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    task_from: systemd